services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snippet-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snippet_db
      SPRING_DATASOURCE_USERNAME: snippet_user
      SPRING_DATASOURCE_PASSWORD: snippet_password
    depends_on:
      - db


  db:
    container_name: snippet_db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: snippet_user
      POSTGRES_PASSWORD: snippet_password
      POSTGRES_DB: snippet_db

    volumes:
      - snippet-data:/var/lib/postgresql/data

volumes:
    snippet-data:

