version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snippet-service
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME:-snippet_db}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRINTSCRIPT_SERVICE_URL: http://printscript-service:8080
      ASSET_SERVICE_URL: http://asset-service:8080
      AUTH_SERVICE_URL: http://auth-service:8081
      AUTH_SERVER_URI: dev-rhvn1b43rtt1hdap.us.auth0.com/
      AUTH0_AUDIENCE: https://my-api-identifier
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - asset-service
      - redis
    networks:
      - shared_network

  db:
    container_name: snippet_db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-snippet_db}
    volumes:
      - snippet-data:/var/lib/postgresql/data
    networks:
      - shared_network

  asset-service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:main.14
    container_name: asset-service
    ports:
      - "8081:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false
    depends_on:
      - azurite
    networks:
      - shared_network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace
    networks:
      - shared_network

  redis:
    image: redis:7-alpine
    container_name: snippet-redis
    ports:
      - "6379:6379"
    networks:
      - shared_network

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8083:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      AUTH0_AUDIENCE: https://my-api-identifier
      AUTH_SERVER_URI: dev-rhvn1b43rtt1hdap.us.auth0.com/
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      - auth-db
    networks:
      - shared_network

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - shared_network

  printscript-service:
    build:
      context: ../printscript-service
      dockerfile: Dockerfile.local
    container_name: printscript-service
    ports:
      - "8080:8080"
    networks:
      - shared_network

volumes:
  snippet-data:
  blob:
  auth-data:

networks:
  shared_network:
    external: true