services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snippet-service
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME:-snippet_db}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRINTSCRIPT_SERVICE_URL: ${PRINTSCRIPT_SERVICE_URL:-http://localhost:8080}
    depends_on:
      - db


  db:
    container_name: snippet_db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-snippet_db}

    volumes:
      - snippet-data:/var/lib/postgresql/data

volumes:
    snippet-data:

